### PR TITLE
Safely handle missing resources

### LINKED ISSUE #283: Handle missing Madmin Resource for associations gracefully
## Problem

When a Resource has an association but the associated model doesn't have a corresponding Madmin Resource defined, the application fails with a constant lookup error instead of gracefully handling the missing Resource.

## Expected Behavior

The application should rescue from the missing constant lookup and either:
- Ignore the attribute entirely, or 
- Handle it gracefully without breaking the Resource display

## Reproduction Steps

This can be simulated in the `test/dummy` app by:
1. Adding a fake association to an existing model, or
2. Temporarily deleting an existing Resource (e.g., delete the `PostResource` class while `User` still has `has_many :posts`)

## Impact

Currently causes application errors when developers haven't created Madmin Resources for all associated models, which should be optional rather than required.

### PR DESCRIPTION
**Pull request by excid3**
Madmin blows up when an attribute references an association where the matching resource is missing. For example, you have Post with `attribute :comments` but `CommentResource` hasn't been created.

This blows up because `Madmin.resource_for(object)` raises an error when looking up the constant. 

To fix this, I've refactored the constant lookup to raise a `Madmin::MissingResource` error. This is rescued in the UI so that we can display an error message instead.

Has many example:
Screenshot 2025-07-28 at 10 41 08 AM

Belongs To example:
Screenshot 2025-07-28 at 10 40 21 AM

Todos:
- [ ] has_many `_form.html.erb` references `field.index_path` which also needs access to the Resource since it uses a remote URL for looking up records
- [ ] We may need to do the same for the other fields for associations.

Closes #283

### CODE REVIEW

File: app/javascript/madmin/controllers/select_controller.js [hunk 1]
```diff
@@ -8,12 +8,15 @@ export default class extends Controller {
...
-    this.select = new TomSelect(this.element, {
+    let options = {
       plugins: ['remove_button'],
       valueField: 'id',
       labelField: 'name',
       searchField: 'name',
-      load: (search, callback) => {
+    }
+
+    if (this.hasUrlValue) {
```
Comment (brandoncc) [inline app/javascript/madmin/controllers/select_controller.js:18]: TIL `has*Value`

File: app/views/madmin/fields/belongs_to/_show.html.erb [hunk 2]
```diff
@@ -1,3 +1,8 @@
 <% if (object = field.value(record)) %>
-  <%= link_to Madmin.resource_for(object).display_name(object), Madmin.resource_for(object).show_path(object), class: "text-blue-500 underline" %>
+  <% begin %>
+    <% associated_resource = Madmin.resource_for(object)%>
+    <%= link_to associated_resource.display_name(object), associated_resource.show_path(object) %>
+  <% rescue Madmin::MissingResource => error %>
```
Comment (brandoncc) [inline app/views/madmin/fields/belongs_to/_show.html.erb]: I wonder how this could be handled without using errors for flow control 🤔 It is very possible this is one of the nicest approaches available to us given the structure of the library. I don't mean that in a bad way, just that every code structure will have certain problems that are not easy to solve.

The nice thing about this approach is that it solves the problem exactly where it is occurring from the UI point of view. Rather than having to have a bunch of conditions and rendering branches internally, a missing resource anywhere in the render code is rendered in a helpful way.

File: lib/madmin/fields/belongs_to.rb [hunk 3]
```diff
@@ -15,8 +15,9 @@ def to_param
         "#{attribute_name}_id"
       end
 
-      def index_path
-        associated_resource.index_path(format: :json)
+      def index_path(format: :json)
+        associated_resource.index_path(format: format)
+      rescue NameError
```
Comment (brandoncc) [inline lib/madmin/fields/belongs_to.rb]: Word of warning, we recently found a bug at work that was caused by a silent `rescue NameError` I had added and it broke something completely unexpected without telling us about it. Perhaps at least a log message should be emitted?

File: lib/madmin/fields/has_many.rb [hunk 4]
```diff
@@ -17,8 +17,13 @@ def to_param
         {"#{attribute_name.to_s.singularize}_ids": []}
       end
 
-      def index_path
-        Madmin.resource_by_name(model.reflect_on_association(attribute_name).klass).index_path(format: :json)
+      def index_path(format: :json)
+        associated_resource.index_path(format: format)
+      rescue NameError
```
Comment (brandoncc) [inline lib/madmin/fields/has_many.rb]: This is purely because I don't have experience with the library, but I don't know why two of the `NameError`s are silent and one re-raises. Can you elaborate? It might be worth a couple of comments as well.

File: app/views/madmin/fields/has_many/_show.html.erb [hunk 5]
```diff
@@ -1,8 +1,9 @@
 <% pagy, records = field.paginated_value(record, params) %>
 <% records.each do |object| %>
-  <div>
-    <%= link_to Madmin.resource_for(object).display_name(object), Madmin.resource_for(object).show_path(object), class: "text-blue-500 underline" %>
-  </div>
+  <% associated_resource = Madmin.resource_for(object) %>
+  <div><%= link_to associated_resource.display_name(object), associated_resource.show_path(object) %></div>
+<% rescue Madmin::MissingResource => error %>
+  <%= tag.div error, class: "error" %>
 <% end %>
```
Comment (brandoncc) [inline app/views/madmin/fields/has_many/_show.html.erb]: This is duplicated in a lot of places. What do you think about something like this?

```erb
<% records.each do |object| %>
  <%= render "associated_resource" do |associated_resource| %>
    <div><%= link_to associated_resource.display_name(object), associated_resource.show_path(object) %></div>
  <% end %>
<% end %>
```

This would allow you to control what is rendered, while putting the error handling in one place:

```erb
<% begin %>
  <% associated_resource = Madmin.resource_for(object) %>
  <%= yield associated_resource %>
<% rescue Madmin::MissingResource => error %>
  <%= tag.div error, class: "error" %>
<% end %>
```

Looking at the code changes in this PR, about half of the renders are in `<div>` tags. This render pattern should support both of these use cases, as well as rendering any other HTML using the resource.

Maybe "with_associated_resource" would be a better partial name, since the render doesn't actually render any HTML of its own unless there is an error? This naming would be reminiscent of the Higher Order Component pattern in React, which is essentially the render pattern used here as well.

**Review by brandoncc — COMMENTED** [review]
I really like how you were able to solve the problem in a much simpler way than I was when I tried to handle the errors at the failing call sites. This approach will likely be simple to maintain, and if complexity arises, can be modified with relative ease.

I do have a few questions, but the only real _concern_ I have is the silent rescues.

File: lib/madmin/fields/belongs_to.rb (hunk 3 above)
Comment (excid3) [reply lib/madmin/fields/belongs_to.rb]: Yeah, good call. I meant to refactor this so `NameError` is only rescued around the `constantize` calls.

**Comment by excid3** [comment]
I refactored this into the fields so that they have a method for retrieving the associated Resource and nil if it doesn't exist. This cleaned up things nicely. 

I left some of the repetition because I expect users to customize fields and their partials, so they should be easy to copy and override.

**Comment by brandoncc** [comment]
This is really nice, I like the changes you made in that refactor commit. Great work!

**Comment by brandoncc** [comment]
Oh, I forgot to mention that I agree with keeping the repetition. I didn't realize that users customize the partials.
